apiVersion: 1

datasources:
  - name: shred-audit
    uid: shredaudit-pg
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    user: postgres
    database: shred_audit
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: postgres
